import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import GoogleSignin from "../src/components/auth/google_oauth";

export default function Header() {
  return (
    <div className={styles.header}>
      <link rel="stylesheet" href="css/main.css" />
      <Head>
        <title>RPMS App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/kuralogo.png" />
        <link href="./css/main.css" rel="stylesheet" />
      </Head>
      <center>
        <a href="/">
          <img src="/kuralogo.png" height="100px"></img>
        </a>
      </center>
      <div>
        <p className={"text-2xl sub"}>Road Progress Monitoring System</p>
      </div>
      <GoogleSignin />
    </div>
  );
}
